---
- name: Install libselinux-python
  yum: name=libselinux-python state=latest

- name: Disable SELinux
  shell: echo 0 > /selinux/enforce

- name: Switch SELinux to permissive mode
  selinux: state=permissive policy=targeted
