---
- hosts: idp
  tasks:
    - include: roles/webserver/main.yml
      notify:
        - start httpd
    
    - include: roles/db/main.yml
      notify:
      - start mysqld
    
    - include: roles/timeserver/main.yml
      notify:
        - start ntpd
    
    - name: Install Java 1.7
      yum: name=java-1.7.0-openjdk state=latest
    
    - name: Install Java 1.7 development package
      yum: name=java-1.7.0-openjdk-devel state=latest
    
    - name: Install ant
      yum: name=ant state=latest
    
    - name: unzip
      yum: name=unzip state=latest

    - include: roles/jspserver/main.yml

  handlers:
    - name: start httpd
      service: name=httpd state=started
    - name: start mysqld
      service: name=mysqld state=started
    - name: start ntpd
      service: name=ntpd state=started
