---
- name: Create destination directory /opt/aaf/shibsrc
  file: path=/opt/aaf/shibsrc state=directory

- name: Download shibboleth IdP
  get_url: url=http://www.shibboleth.net/downloads/identity-provider/{{idp_version}}/shibboleth-identityprovider-{{idp_version}}-bin.zip dest=/opt/aaf

- name: unzip shibboleth IdP
  unarchive: src=/opt/aaf/shibboleth-identityprovider-{{idp_version}}-bin.zip dest=/opt/aaf/shibsrc

- name: Resolve shibboleth IdP keystore password
  set_fact:
    idp_storepass: "{{ lookup('password', '/opt/aaf/credentials/' + server_name + '/idp-storepass chars=letters,digits length=64') }}"

- name: Create install script
  template: >
    src=install-idp.sh.j2 dest=/opt/aaf/shibsrc/install-{{idp_version}}.sh
    owner=root group=root mode=0750

- name: Install shibboleth IdP
  command: >
    /opt/aaf/shibsrc/install-{{idp_version}}.sh
    creates=/opt/shibboleth-idp/

- name: Create logs directory
  file: path=/opt/shibboleth-idp/logs state=directory owner=root group=tomcat mode=0774 recurse=yes


- name: Create credentials directory
  file: path=/opt/shibboleth-idp/credentials state=directory owner=root group=tomcat mode=0770

- name: Download certificates (Test environment)
  get_url: >
    url=https://ds.test.aaf.edu.au/distribution/metadata/metadata-cert.pem
    dest=/opt/shibboleth-idp/credentials/aaf-metadata-cert.pem
  when: {{environment_type}} == "Test"

- name: Download certificates (Production environment)
  get_url: >
    url=https://ds.aaf.edu.au/distribution/metadata/metadata-cert.pem
    dest=/opt/shibboleth-idp/credentials/aaf-metadata-cert
  when: {{environment_type}} == "Production"


- name: Change permissions for /opt/shibboleth-idp directory
  file: path=/opt/shibboleth-idp/ owner=root group=tomcat recurse=yes

- name: Change permissions for /opt/shibboleth-idp/war/idp.war file
  file: path=/opt/shibboleth-idp/war/idp.war mode=0664

- name: Start tomcat
  service: name=tomcat state=started
