---
- name: Installs mariadb
  yum: pkg=mariadb state=latest

- name: Installs mariadb-server
  yum: pkg=mariadb-server state=latest
  notify: start mysqld

- meta: flush_handlers

- name: Create /root/mysql_secure_installation.sql
  template: src=mysql_secure_installation.sql.j2 dest=/root/mysql_secure_installation.sql owner=root mode=0600

- name: Run /root/mysql_secure_installation.sql
  command: 'mysql -e "source /root/mysql_secure_installation.sql"'
