---
- name: Installs mariadb
  yum: pkg=mariadb state=latest
  when: ansible_distribution == 'CentOS' and ansible_distribution_version >= '7'

- name: Installs mysql
  yum: pkg=mysql state=latest
  when: ansible_distribution == 'CentOS' and ansible_distribution_version >= '6' and ansible_distribution_version < '7'

- name: Installs mariadb-server
  yum: pkg=mariadb-server state=latest
  when: ansible_distribution == 'CentOS' and ansible_distribution_version >= '7'
  notify: start mariadb-server

- name: Installs mysql-server
  yum: pkg=mysql-server state=latest
  when: ansible_distribution == 'CentOS' and ansible_distribution_version >= '6' and ansible_distribution_version < '7'
  notify: start mysqld

- meta: flush_handlers

- name: Create /root/mysql_secure_installation.sql
  template: src=mysql_secure_installation.sql.j2 dest=/root/mysql_secure_installation.sql owner=root mode=0600

- name: Run /root/mysql_secure_installation.sql
  command: 'mysql -e "source /root/mysql_secure_installation.sql"'
