---
- name: Download Tomcat 7.0.42
  get_url: url=http://archive.apache.org/dist/tomcat/tomcat-7/v7.0.42/bin/apache-tomcat-7.0.42.tar.gz
                 dest=/opt/apache-tomcat-7.0.42.tar.gz

- name: Extract archive
  command: /bin/tar xvf /opt/apache-tomcat-7.0.42.tar.gz -C /opt/
        creates=/opt/apache-tomcat-7.0.42

- name: Delete default apps
  file: path=/opt/apache-tomcat-7.0.42/webapps/{{ item }} state=absent
  with_items:
    - docs
    - examples
    - host-manager
    - manager
    - ROOT

- name: Add tomcat group
  group: name=tomcat
- name: Add tomcat user
  user: name=tomcat group=tomcat home=/opt/apache-tomcat-7.0.42
- name: Change tomcat permissions
  file: path=/opt/apache-tomcat-7.0.42/ owner=tomcat group=tomcat state=directory recurse=yes

- name: Write /opt/apache-tomcat-7.0.42/conf/server.xml
  copy: >
    src=server.xml dest=/opt/apache-tomcat-7.0.42/conf/server.xml
    owner=tomcat group=tomcat mode=0600
  notify: restart tomcat

- name: Start tomcat
  shell: /opt/apache-tomcat-7.0.42/bin/startup.sh
