---
- name: Download Tomcat
  get_url: url=http://archive.apache.org/dist/tomcat/tomcat-7/v{{tomcat_version}}/bin/{{tomcat_filename}}-{{tomcat_version}}.tar.gz
                 dest=/opt/{{tomcat_filename}}-{{tomcat_version}}.tar.gz

- name: Extract archive
  command: /bin/tar xvf /opt/{{tomcat_filename}}-{{tomcat_version}}.tar.gz -C /opt/
        creates=/opt/{{tomcat_filename}}-{{tomcat_version}}

- name: Delete default apps
  file: path=/opt/{{tomcat_filename}}-{{tomcat_version}}/webapps/{{ item }} state=absent
  with_items:
    - docs
    - examples
    - host-manager
    - manager
    - ROOT

- name: Add tomcat group
  group: name=tomcat
- name: Add tomcat user
  user: name=tomcat group=tomcat home=/opt/{{tomcat_filename}}-{{tomcat_version}}
- name: Change tomcat permissions
  file: path=/opt/{{tomcat_filename}}-{{tomcat_version}}/ owner=tomcat group=tomcat state=directory recurse=yes

- name: Write /opt/tomcat/conf/server.xml
  copy: >
    src=server.xml dest=/opt/{{tomcat_filename}}-{{tomcat_version}}/conf/server.xml
    owner=tomcat group=tomcat mode=0600
  notify: restart tomcat

- name: Write /opt/tomcat/bin/setenv.sh
  copy: >
    src=setenv.sh dest=/opt/{{tomcat_filename}}-{{tomcat_version}}/bin/setenv.sh
    owner=tomcat group=tomcat mode=0755
  notify: restart tomcat

- name: create tomcat symlink
  file: path=/opt/tomcat state=link src=/opt/{{tomcat_filename}}-{{tomcat_version}}

- name: Symlink endorsed libs into Tomcat endorsed
  file: >
    path=/opt/tomcat/endorsed
    src=/opt/aaf/shibsrc/shibboleth-identityprovider-{{idp_version}}/endorsed
    state=link owner=tomcat group=tomcat
  notify: restart tomcat

- name: Write /lib/systemd/system/tomcat.service
  copy: >
    src=tomcat.service dest=/lib/systemd/system/tomcat.service
    owner=root mode=644
  notify: restart tomcat

- name: Enable tomcat startup on boot
  service: name=tomcat enabled=yes

- name: Start tomcat
  service: name=tomcat state=started
