---
- name: Download uApprove
  get_url: >
    url=http://www.switch.ch/aai/downloads/uApprove-{{ uapprove_version }}.zip
    dest=/opt/aaf/shibsrc/

- name: Extract archive
  unarchive: >
    src=/opt/aaf/shibsrc/uApprove-{{ uapprove_version }}.zip
    dest=/opt/aaf/shibsrc/

- name: Copy over uApprove libraries
  copy: >
    src={{ item }}
    dest=/opt/aaf/shibsrc/shibboleth-identityprovider-{{ idp_version }}/lib
  with_fileglob:
    - /opt/aaf/shibsrc/uApprove-{{ uapprove_version }}/*.jar
    - /opt/aaf/shibsrc/uApprove-{{ uapprove_version }}/jdbc/*.jar