---
- name: Download uApprove
  get_url: >
    url=http://www.switch.ch/aai/downloads/uApprove-{{ uapprove_version }}.zip
    dest=/opt/aaf/shibsrc/

- name: Extract archive
  unarchive: >
    src=/opt/aaf/shibsrc/uApprove-{{ uapprove_version }}.zip
    dest=/opt/aaf/shibsrc/

- name: Copy over uApprove libraries
  copy: >
    src={{ item }}
    dest=/opt/aaf/shibsrc/shibboleth-identityprovider-{{ idp_version }}/lib
  with_fileglob:
    - /opt/aaf/shibsrc/uApprove-{{ uapprove_version }}/lib/*.jar
    - /opt/aaf/shibsrc/uApprove-{{ uapprove_version }}/lib/jdbc/*.jar

- name: Copy over JDBC connector
  copy: >
    src=/opt/aaf/shibsrc/uApprove-{{ uapprove_version }}/lib/jdbc/optional/mysql-connector-java-5.1.25.jar
    dest=/opt/aaf/shibsrc/shibboleth-identityprovider-{{ idp_version }}/lib

- name: Make uApprove directory in webapp directory
  file: >
    path=/opt/aaf/shibsrc/shibboleth-identityprovider-{{ idp_version }}/src/main/webapp/uApprove
    state=directory

- name: Copy over web application files to IdP webapp directory
  copy: >
    src={{ item }}
    dest=/opt/aaf/shibsrc/shibboleth-identityprovider-{{ idp_version }}/src/main/webapp/uApprove
  with_fileglob:
    - /opt/aaf/shibsrc/uApprove-{{ uapprove_version }}/webapp/*

- name: Copy over terms-of-use.html to /opt/shibboleth-idp/conf directory
  copy: src=terms-of-use.html dest=/opt/shibboleth-idp/conf
  when: tou == true

- name: Resolve mysql password
  set_fact:
    mysql_passwd: "{{ lookup('password', '/root/.mysql_password chars=letters,digits length=64') }}"

- name: Write uApprove.xml to /opt/shibboleth-idp/conf
  copy: src=uApprove.xml dest=/opt/shibboleth-idp/conf

- name: Write uApprove.properties to /opt/shibboleth-idp/conf
  template: src=uApprove.properties.j2 dest=/opt/shibboleth-idp/conf/uApprove.properties

- name: Create /root/uapprove_db_setup.sql
  template: src=uapprove_db_setup.sql.j2 dest=/root/uapprove_db_setup.sql owner=root mode=0600

- name: Run /root/uapprove_db_setup.sql
  command: 'mysql -e "source /root/uapprove_db_setup.sql"'

- name: Create /root/my.cnf
  template: src=my.cnf.j2 dest=/root/my.cnf owner=root mode=0600

- name: Restart mariadb-server
  service: name=mariadb state=restarted

- name: Write new web.xml file over old one
  template: src=web.xml.j2 dest=/opt/aaf/shibsrc/shibboleth-identityprovider-{{ idp_version }}/src/main/webapp/WEB-INF/web.xml

- name: Remove log folder deletion clause from custom install script
  lineinfile: >
    dest=/opt/aaf/shibsrc/install-{{ idp_version }}.sh
    line="rmdir /opt/shibboleth-idp/logs"
    state=absent

- name: Redeploy IdP
  command: /opt/aaf/shibsrc/install-{{ idp_version }}.sh
