---
- name: Download uApprove
  get_url: >
    url=http://www.switch.ch/aai/downloads/uApprove-{{ uapprove_version }}.zip
    dest=/opt/aaf/shibsrc/

- name: Extract archive
  unarchive: >
    src=/opt/aaf/shibsrc/uApprove-{{ uapprove_version }}.zip
    dest=/opt/aaf/shibsrc/

- name: Copy over uApprove libraries
  copy: >
    src={{ item }}
    dest=/opt/aaf/shibsrc/shibboleth-identityprovider-{{ idp_version }}/lib
  with_fileglob:
    - /opt/aaf/shibsrc/uApprove-{{ uapprove_version }}/lib/*.jar
    - /opt/aaf/shibsrc/uApprove-{{ uapprove_version }}/lib/jdbc/*.jar

- name: Copy over JDBC connector
  copy: >
    src=/opt/aaf/shibsrc/uApprove-{{ uapprove_version }}/lib/jdbc/optional/mysql-connector-java-5.1.25.jar
    dest=/opt/aaf/shibsrc/shibboleth-identityprovider-{{ idp_version }}/lib

- name: Make uApprove directory in webapp directory
  file: >
    path=/opt/aaf/shibsrc/shibboleth-identityprovider-{{ idp_version }}/src/main/webapp/uApprove
    state=directory

- name: Copy over web application files to IdP webapp directory
  copy: >
    src={{ item }}
    dest=/opt/aaf/shibsrc/shibboleth-identityprovider-{{ idp_version }}/src/main/webapp/uApprove
  with_fileglob:
    - /opt/aaf/shibsrc/uApprove-{{ uapprove_version }}/webapp/*

- name: Copy over configuration templates
  copy: src={{ item }} dest=/opt/shibboleth-idp/conf
  with_items:
    - uApprove.xml
    - uApprove.properties